version: '3'

services:
  db:
    container_name: 'db_psql'
    image: postgres
    env_file:
      - ./.envs/.env
    ports:
      - 54320:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  python_service:
    container_name: 'python_container'
    build: .
    volumes:
      - ./:/usr/application/teste
    depends_on:
      - db
    env_file:
      - ./.envs/.app.env
    tty: true
    stdin_open: true
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis/redis-persistence:/bitnami
  airflow-scheduler:
    container_name: 'airflow_scheduler'
    image: docker.io/bitnami/airflow-scheduler:2
    env_file:
      - ./.envs/.airflow.env
    environment:
    - AIRFLOW_WEBSERVER_HOST=airflow
    depends_on:
      - db
      
  airflow-worker:
    container_name: 'airflow_worker'
    image: docker.io/bitnami/airflow-worker:2
    env_file:
      - ./.envs/.airflow.env
    environment:
      - AIRFLOW_WEBSERVER_HOST=airflow
    depends_on:
      - db
  airflow:
    container_name: 'airflow'
    image: docker.io/bitnami/airflow:2
    env_file:
      - ./.envs/.airflow.env
    volumes:
      - ./src/dags:/opt/bitnami/airflow/dags
      - ./requirements.txt:/bitnami/python/requirements.txt
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - db
        