version: '3'

services:
  db:
    container_name: 'db_psql'
    image: bitnami/postgresql
    env_file:
      - ./.envs/.env
    ports:
      - 54320:5432
    volumes:
      - ./pgdata:/bitnami/postgresql
  python_service:
    container_name: 'python_container'
    build: .
    volumes:
      - ./:/usr/application/teste
    depends_on:
      - db
    env_file:
      - ./.envs/.app.env
    tty: true
    stdin_open: true
  airflow-scheduler:
    image: docker.io/bitnami/airflow-scheduler:2
    env_file:
      - ./.envs/.airflow.env
      - ./.envs/.airflow-host.env
  airflow-worker:
    image: docker.io/bitnami/airflow-worker:2
    env_file:
      - ./.envs/.airflow.env
      - ./.envs/.airflow-host.env
  airflow:
    image: docker.io/bitnami/airflow:2
    env_file:
      - ./.envs/.airflow.env
      - ./.envs/.airflow-db.env
    ports:
      - 8080:8080